package Algorithms.Leetcode;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 *
 * Created by dianaluca on 9/13/16.
 */

public class FindTheDifference389 {
  public static char findTheDifference(String s, String t) {
    if (s.length() >= t.length()) return (char) -1;
    for (int i = 0; i < t.length(); i++) {
      int j = 0;
      while ((j < s.length()) && (t.charAt(i) != s.charAt(j))) {
        j++;
      }
      if (j >= s.length()) return t.charAt(i);
    }
    return (char) -1;
  }

  //Solution 2: XOR ----------------------------------------------

  public static char findTheDifferenceXOR(String s, String t) {
    char xorR = 0;
    for (int i = 0; i < s.length(); i++) {
      xorR ^= s.charAt(i);
    }
    for (int j = 0; j < t.length(); j++) {
      xorR ^= t.charAt(j);
    }
    return xorR;
  }

  //Test Client:

  public static void main(String[] args) {
    System.out.println(findTheDifference("abcd", "dbcae"));
  }
}
