"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def evenFib(x):
    a = 1
    b = 2
    c = a + b
    sumf = b
    while c <= x:
        a = b
        b = c
        c = a + b
        print(a,b,c)
        if c <= x and c % 2 == 0:
            sumf += c

    return sumf


def main():
    print(evenFib(10))
    print(evenFib(100))
    print(evenFib(4000000))

if __name__ == '__main__':
    main()