# Given two strings s and t which consist of only lowercase letters.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Find the letter that was added in t.

# Input:
# s = "abcd"
# t = "abcde"
# Output:
# e
# 'e' is the letter that was added.

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        ds, dt = {}, {}
        for el in s:
            if el in ds:
                ds[el] += 1
            else:
                ds[el] = 1
        for el in t:
            if el in dt:
                dt[el] += 1
            else:
                dt[el] = 1

        for key in ds.keys():
            if key in ds and key in dt:
                if ds[key] != dt[key]:
                    return key
            else:
                return key
        for key in dt.keys():
            if key not in ds:
                return key

    def findTheDifferenceXOR(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """

        # ord('a') = 97
        # chr(97) = 'a'

        if not s:
            return t
        if not t:
            return ""

        res = ''
        for el in s:
            if not res:
                res = el
            else:
                res = chr(ord(res) ^ ord(el))
        for el in t:
            res = chr(ord(res) ^ ord(el))
        return res
